fails:Exception#exception when raised will be rescued as the new exception
